CREATE DATABASE dbclientes;


CREATE TABLE dbclientes.clientes
(
  ClienteId INT NOT NULL AUTO_INCREMENT,
  Apellido VARCHAR(100) NOT NULL,
  Nombre VARCHAR(100) NOT NULL,
  DNI VARCHAR(8) NOT NULL,
  Domicilio VARCHAR(100) NOT NULL,
  Email VARCHAR(100) NOT NULL,
  PRIMARY KEY (ClienteId),
  UNIQUE INDEX DNI_UNIQUE (DNI ASC)
);